% -------------------------------------------------------------------
%  Generated by MATLAB on 11-May-2020 14:24:32
%  MATLAB version: 9.6.0.1214997 (R2019a) Update 6
% -------------------------------------------------------------------
saveVarsMat = load('emission_led.mat');

emissionled = saveVarsMat.emissionled; % <651x2 double> too many elements

clear saveVarsMat;
